PP-10717: Upgrade Docker Java image
alphagov/pay-adminusers pull request #1882
Opened 2023-02-20 17:24 UTC by oswaldquek

2023-02-20 18:16 UTC, nlsteers requested changes
Don't forget to update the ARM64 Dockerfile as well

2023-02-21 09:44 UTC, oswaldquek commented
@nlsteers fixed

2023-02-21 10:10 UTC, nlsteers commented on m1/arm64.Dockerfile
> +FROM eclipse-temurin:11.0.18_10-jre-alpine@sha256:4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad
I think you will need to use an ARM-specific SHA here. Alpine doesn't provide an ARM variant which is why the images are different (`jre` vs `jre-alpine`).

```suggestion
FROM eclipse-temurin:11-jre
@sha256:dd745f7e5a780d432ea24c9936721271e74853c712a58461c47aecd315ef5701
```

2023-02-21 11:15 UTC, nlsteers approved these changes

2023-02-21 11:24 UTC, merged