Pp 13030 role name enum
alphagov/pay-adminusers pull request #2657
Opened 2024-09-10 14:02 UTC by oswaldquek

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2024-09-11 23:02 UTC, alexbishop1 requested changes
I’m in favour of this change. Just a few minor things.

2024-09-11 23:02 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteIT.java
> +    public void setUp() {
`public` is unnecessary here.

2024-09-12 09:00 UTC, oswaldquek commented on src/main/java/uk/gov/pay/adminusers/model/RoleName.java
> +        return roleName.get();
Thanks. I'll go with the last suggestion as it's technically the most performant.

2024-09-12 10:00 UTC, oswaldquek commented
> I’m in favour of this change. Just a few minor things.

Yay 🥳

2024-09-12 14:05 UTC, alexbishop1 approved these changes

2024-09-12 14:08 UTC, merged